import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} font-sans antialiased`} // Apply the Roboto font
      >
        <AuthProvider>
          <Navbar />
          {children}
          <Toaster/>
        </AuthProvider>
      </body>
    </html>
  );
}